[project]
name = "opt-strategy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "nltk>=3.9.1",
    "numpy>=2.1.3",
    "pyyaml>=6.0.2",
    "sentencepiece>=0.2.0",
    "torch>=2.5.1",
    "tqdm>=4.66.6",
]
